import {
  TypescriptIcon,
  JavascriptIcon,
  CSSIcon,
  SassIcon,
  ReactIcon,
  SvelteIcon,
  ArduinoIcon,
  AngularIcon,
  DockerIcon,
  ExpoIcon,
  GitIcon,
  GithubIcon,
  HtmlIcon,
  FigmaIcon,
  JQueryIcon2,
  NestJsIcon,
  MuiIcon,
  MySqlIcon,
  PostgresIcon,
  PostmanIcon,
  ReduxIcon,
  NextJsIcon,
  ViteIcon,
  TailwindIcon,
  ThreeJsIcon,
  ObsidianIcon,
} from "../icons";
import { ISkillObject } from "../types";

export const SKILLS: ISkillObject[] = [
  {
    name: "Typescript",
    description: "typescript_description",
    icon: TypescriptIcon,
    level: 11,
    color: "#007ACC",
  },
  {
    name: "Javascript",
    description: "javascript_description",
    icon: JavascriptIcon,
    level: 11,
    color: "#F0DB4F",
  },
  {
    name: "HTML",
    description: "html_description",
    icon: HtmlIcon,
    level: 11,
    color: "#E14E1D",
  },
  {
    name: "CSS",
    description: "css_description",
    icon: CSSIcon,
    level: 11,
    color: "#0277BD",
  },
  {
    name: "Sass",
    description: "sass_description",
    icon: SassIcon,
    level: 11,
    color: "#CD6799",
  },
  {
    name: "React",
    description: "react_description",
    icon: ReactIcon,
    level: 11,
    color: "#00D8FF",
  },
  {
    name: "NextJs",
    description: "nextjs_description",
    icon: NextJsIcon,
    level: 7,
    color: "#FFFFFF",
  },
  {
    name: "Mui",
    description: "mui_description",
    icon: MuiIcon,
    level: 10,
    color: "#164A83",
  },
  {
    name: "Redux",
    description: "redux_description",
    icon: ReduxIcon,
    level: 8,
    color: "#764ABC",
  },
  {
    name: "Tailwind",
    description: "tailwind_description",
    icon: TailwindIcon,
    level: 7,
    color: "#27B8BD",
  },
  {
    name: "Svelte",
    description: "svelte_description",
    icon: SvelteIcon,
    level: 9,
    color: "#FF3E00",
  },
  {
    name: "Angular",
    description: "angular_description",
    icon: AngularIcon,
    level: 8,
    color: "#E23237",
  },
  {
    name: "ThreeJs",
    description: "threejs_description",
    icon: ThreeJsIcon,
    level: 9,
    color: "#F0F0F0",
  },
  {
    name: "React Native / Expo",
    description: "react_native_expo_description",
    icon: ExpoIcon,
    level: 9,
    color: "#4630EB",
  },
  {
    name: "Postman",
    description: "postman_description",
    icon: PostmanIcon,
    level: 10,
    color: "#FF6C37",
  },
  {
    name: "MySql",
    description: "mysql_description",
    icon: MySqlIcon,
    level: 10,
    color: "#08668E",
  },
  {
    name: "Vite",
    description: "vite_description",
    icon: ViteIcon,
    level: 9,
    color: "#6E99FF",
  },
  {
    name: "Postgres",
    description: "postgres_description",
    icon: PostgresIcon,
    level: 9,
    color: "#336791",
  },
  {
    name: "NestJs",
    description: "nestjs_description",
    icon: NestJsIcon,
    level: 7,
    color: "#E0234E",
  },
  {
    name: "Docker",
    description: "docker_description",
    icon: DockerIcon,
    level: 7,
    color: "#2496ED",
  },
  {
    name: "Git",
    description: "git_description",
    icon: GitIcon,
    level: 8,
    color: "#F34F29",
  },
  {
    name: "Github",
    description: "github_description",
    icon: GithubIcon,
    level: 10,
    color: "#F0F6FC",
  },
  {
    name: "JQuery",
    description: "jquery_description",
    icon: JQueryIcon2,
    level: 10,
    color: "#0769AD",
  },
  {
    name: "Figma",
    description: "figma_description",
    icon: FigmaIcon,
    level: 7,
    color: "#F24E1E",
  },
  {
    name: "Arduino",
    description: "arduino_description",
    icon: ArduinoIcon,
    level: 6,
    color: "#00979D",
  },
  {
    name: "Obsidian",
    description: "obsidian_description",
    icon: ObsidianIcon,
    level: 8,
    color: "#5D33B0",
  },
];

// <span>Frontend</span> <span>React, Redux, TypeScript, SCSS</span>
// <span>Backend</span> <span>Node.js, Express, MongoDB, MySQL</span>
// <span>DevOps</span> <span>Docker, Kubernetes, Jenkins</span>
// <span>Cloud</span> <span>AWS, GCP, Azure</span>
// <span>CI/CD</span> <span>GitHub Actions, Travis CI, Circle CI</span>
// <span>Testing</span> <span>Jest, React Testing Library, Mocha</span>
// <span>Other</span> <span>Git, Agile, Scrum, Kanban, Jira</span>
